/* sélectionne les USERS possédant le ROLE 'ROLE_ADMINISTRATEUR - TOUT'. */
SELECT * FROM USERS WHERE USERS.ID IN
(SELECT USERS_ROLES.USER_ID FROM USERS_ROLES 
WHERE USERS_ROLES.ROLE_ID = (SELECT ID FROM ROLES WHERE ROLES.ROLE = 'ROLE_ADMINISTRATEUR - TOUT'));